server:
  port: 8085
spring:
  application:
    name: core-banking-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
