server:
  port: 8082
spring:
  application:
    name: internet-banking-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: internet-banking-user-service
          uri: lb://internet-banking-user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: internet-banking-fund-transfer-service
          uri: lb://internet-banking-fund-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - RewritePath=/fund-transfer/(?<segment>.*), /$\{segment}
        - id: core-banking-service
          uri: lb://core-banking-service
          predicates:
            - Path=/core/**
          filters:
            - RewritePath=/core/(?<segment>.*), /$\{segment}
        - id: internet-banking-utility-payment-service
          uri: lb://internet-banking-utility-payment-service
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /$\{segment}
        - id: internet-banking-statement-service
          uri: lb://internet-banking-statement-service
          predicates:
            - Path=/statement/**
          filters:
            - RewritePath=/statement/(?<segment>.*), /$\{segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/javatodev-internet-banking/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
